### PR TITLE
Add 140

### PR DESCRIPTION
**Pull request by rm-code**
#### Design and programming ####
Jeppe Carlsen

#### Audio ####
Jakob Schmid

#### Visual concept ####
Andreas Peitersen
Niels Fyrst

### CODE REVIEW

**Comment by rm-code** [comment]
@Yonaba It won the "Excellence in Audio award at IGF 2013" and you can find articles about it all over the internet.

**Comment by Yonaba** [comment]
My main concern abou this entry is, it seems right from the start, **it was the work of a team**. 
How did the frst public release went out ? Did the programmer code all the prototype alone ? And then the others joined him to work on the following releases ?

**Comment by rm-code** [comment]
Ah I see. I'm not sure if the people listed in the credits were in fact part of a team or external contributors.

In any case may I suggest adjusting the CONTRIUBTING.md? While the title of the list is pretty clear IMO this paragraph is a bit confusing:

> It must have been __entirely programmed and designed by only one person__. This person might have made the assets, music, production, or might have gotten _some extra-help for those parts_, or might have bought/purchased or obtained them for free. But indeed, at the very minimum least, __the entire programming and design__ should have been done by __a single person__.

Where do we draw the line at the "extra-help" part?

**Comment by Yonaba** [comment]
> In any case may I suggest adjusting the CONTRIUBTING.md? While the title of the list is pretty clear IMO this paragraph is a bit confusing. Where do we draw the line at the "extra-help" part?

I suggest opening a new ticket for that. We can discuss about it there.

**Pull request closed without merging**
