### PR TITLE
Add Cogmind

### PR DESCRIPTION
**Pull request by rm-code**

### CODE REVIEW

**Comment by Yonaba** [comment]
Awesome. 
Would you please edit the addition to remove the `(Grid Sage Game)` part ?
Only the developer name is required, ended by a full period.

**Comment by rm-code** [comment]
@Yonaba Done. I also removed the accidental insertion of a newline at the end of the file.

**Comment by rm-code** [comment]
Argh wait a second... I forgot the fullstop.

**Comment by rm-code** [comment]
Ok now it should be ok 👍

**Comment by Yonaba** [comment]
Awesome. Thanks.

**Pull request merged**
