### PR TITLE
Add Going Home

### PR DESCRIPTION
**Pull request by flamendless**
It was here before, idk why's it gone

### CODE REVIEW

**Comment by rm-code** [comment]
I think it probably doesn't match the [contribution guidelines](https://github.com/Yonaba/awesome-one-person-games/blob/master/contributing.md).

> It should have a substantial media exposure. For example, it should be easy to find over the Internet, have a public website or a project page on popular indie gamedev boards (such as IndieDB, Steam, ...).

> It should have received good critics and good ratings over the Internet and forums. Being featured on popular gaming news boards (IGN, Gamasutra, GamesRadar+, GameSpew, ...) would be a plus.

**Comment by flamendless** [comment]
It does meet the requirements. Easy to find. In Gamejolt (thats th indie version of steam). Has a public website. 

It is also positively received by the community. Over 70+ followers. High ratings and very positive comments. It is also going to be in an article in a tv network here in our country.
www.gmanetwork.com/news/scitech/technology/616075/pinoy-teen-creates-pixel-art-horror-game-going-home/story/

**Comment by flamendless** [comment]
Here's the national tv article i was talking about www.gmanetwork.com/news/scitech/technology/616075/pinoy-teen-creates-pixel-art-horror-game-going-home/story/

**Comment by Yonaba** [comment]
@flamendless, nice addition.
Would you please update your commit and append "http://" at the beginning of the URL link pointing to GameJolt? And also, do not forget to add a dot character at the end of the line, right after the author name.

**Comment by flamendless** [comment]
@Yonaba there you go. Thank you :)

**Comment by rm-code** [comment]
> Here's the national tv article i was talking about www.gmanetwork.com/news/scitech/technology/616075/pinoy-teen-creates-pixel-art-horror-game-going-home/story/

Cool article and always nice to see games made with LÖVE :)

👍

**Comment by flamendless** [comment]
Thank you

**Comment by Yonaba** [comment]
Thanks for your entry, @flamendless!

**Pull request merged**
